### ISSUE TITLE
Autoencoder says GAN in places

### ISSUE THREAD

**Issue by chadcwilliams** [AutoResearch/EEG-GAN#64] opened 2023-11-10 20:45 UTC
In the parameters and when saving the model.

**Comment by whyhardt** [comment] 2024-04-16 09:30
Fixed in system_inputs.py

Could not reproduce for saving the model:
```
-----------------------------------------
Command line arguments:
-----------------------------------------

Number of epochs: 1
-----------------------------------------

Training the first level of the autoencoder...
100%|██████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.29it/s, TRAIN LOSS: 0.018711, TEST LOSS: 0.012502]
Managing checkpoints...
Training the second level of the autoencoder...
100%|██████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.48it/s, TRAIN LOSS: 0.018746, TEST LOSS: 0.013592]
Managing checkpoints...
Training finished.
Model and configuration saved in trained_ae/ae_gansEEGTrainingData_1713259748.pt
```

**Closed by whyhardt** 2024-04-16 09:30 UTC
Labels: priority 2: wanted, autoencoder
